artifacts_root: src/artifacts

data_ingestion:
  root_dir: src/artifacts/data_ingestion
  source_URL: https://github.com/nisha132/Datasets/raw/refs/heads/main/Chicken-fecal-images.zip
  local_data_file: src/artifacts/data_ingestion/data.zip
  unzip_dir: src/artifacts/data_ingestion


prepare_base_model:
  root_dir: src/artifacts/prepare_base_model
  base_model_path: src/artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: src/artifacts/prepare_base_model/updated_base_model.h5

prepare_callbacks:
  root_dir: src/artifacts/prepare_callbacks
  tensorboard_log_dir: src/artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: src/artifacts/prepare_callbacks/checkpoint_dir/model.h5



  